name: docker_release_rust

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - crawler
          - job-manager
          - extractor
          - add-uuid
          - diff
          - publish
          - archive
          - sync-consumer
          - cleanup
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nbittich/${{ matrix.service }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64 #,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CRATE_NAME=${{ matrix.service }}
          cache-from: type=registry,ref=nbittich/${{ matrix.service }}:buildcache
          cache-to: type=registry,ref=nbittich/${{ matrix.service }}:buildcache,mode=max
