name: docker_latest_java

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./filter
          file: ./filter/Dockerfile
          push: true
          tags: nbittich/filter:latest
          cache-from: type=registry,ref=nbittich/filter:buildcache
          cache-to: type=registry,ref=nbittich/filter:buildcache,mode=max
          platforms: linux/amd64 #,linux/arm64
